# Estructuras de datos

## Vectores

Anteriormente hemos creado vectores de longitud 1 cuando guardamos en un objeto un único número.
También observamos que podemos crear vectores con las funciones `c()` y `scan()`.

Pero también podemos crearlos con secuencias, repeticiones, y la función `paste()`   

In [7]:
#Generando secuencias de datos 
#Operador
1:8
#Función seq()
seq (1,8)
seq (1,8, by= .5) # Cambiando valores por defecto de los argumentos
a <- seq (1,8, length=15)
a
#Función rep()
rep (7,5)
rep (1:5,3)
b <- rep (c("A", "B", "C"), 3)
b
#Función paste()
paste("T",1:4)
c <- paste("T",1:4,sep=".")
c

[1] 1 2 3 4 5 6 7 8

[1] 1 2 3 4 5 6 7 8

[1] 1.0 1.5 2.0 2.5 3.0 3.5 4.0 4.5 5.0 5.5 6.0 6.5 7.0 7.5 8.0

[1] 1.0 1.5 2.0 2.5 3.0 3.5 4.0 4.5 5.0 5.5 6.0 6.5 7.0 7.5 8.0

[1] 7 7 7 7 7

[1] 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5

[1] "A" "B" "C" "A" "B" "C" "A" "B" "C"

[1] "T 1" "T 2" "T 3" "T 4"

[1] "T.1" "T.2" "T.3" "T.4"

Una de las principales características más importantes de R es la posibilidad de usar un vector como argumento de las funciones y así utilizar todos los elementos del mismo.

In [8]:
# Crear un vector x de 15 números
# Aplicar función max()
# Crear un vector d con los vectores a, b, c

Existirán otras veces en las que necesitaremos acceder específicamente a un elemento del vector, como este tiene una sola dimensión, ubicaremos entre `[]` la posición del elemento a escoger. En R el índice comienza en 1.

In [3]:
# Seleccionar el elemento 7 de x
# Seleccitud 5ionar elementos del 9 al 12

Podemos ordenar el vector en forma ascendente o decreciente con la función `sort()` y encontrar su longitud con `length()`.

In [ ]:
# Ordenar x en orden ascendente
# Averiguar la longitud de x

### Operaciones con vectores

Suma, resta, división, exponenciación, se definen de elemento a elemento entre vectores

In [22]:
# Suma entre dos vectores de longitud 4
# Resta de dos vectores de longitud 2
# Multiplicación de dos vectores de longitud 3
# Eleva a potencia 
    #(2, 3, 4)^(3:1)
#Probemos los operadores lógicos >,<,=

## Data Frame


Es un objeto bidimensional (filas x columnas).

R trata las columnas (llamadas variables) como distintas variables (mismo tipo) y las filas(llamadas records) representan las observaciones (diferentes tipos).
Los Data Frames son rectangulares y los espacios vacíos se llenan con NA, **sus elementos tienen la misma longitud**.

Se pueden crear con la funcion `data.frame()` y puedes seleccionar una columna usando el operador `$`. 



In [14]:
# Creemos 3 vectores l, m, n de longitud 6
name <- c("Ana", "Daniel", "Chris", "Mary", "Albert", "Flor", "Gendry")
gender <- c("F", "M", "M", "F", "M", "F", "M")
age <- c(23, 27, 54, 34, 46, 22, 45)
datos <- data.frame(name, gender, age)
datos

name   gender age
1 Ana    F      23 
2 Daniel M      27 
3 Chris  M      54 
4 Mary   F      34 
5 Albert M      46 
6 Flor   F      22 
7 Gendry M      45

La mayoría de las veces nos vamos a encontrar con bases de datos gigantes, que no va a ser muy práctico desplegar en la consola, por lo que R presenta varias funciones que nos permiten extraer información y observar algunas características de los datos. Veamos algunas:

Carguemos un conjunto de datos, utilizando la función `data()` (podemos encontrar más información sobre los conjuntos de datos en wikipedia, por ejemplo: https://es.wikipedia.org/wiki/Iris_flor_conjunto_de_datos )

In [ ]:
data()
# Elegir un dataset y aplicar las siguientes funciones
# head()
# tail()
# fix()
# edit()
# str()
# summary()

Podemos conocer algunas características del data frame con las siguientes funciones:

In [20]:
nrow() #Introducir dentro del paréntesis el conjunto seleccionado
ncol()
dim ()

ERROR: Error in nrow(): el argumento "x" está ausente, sin valor por omisión


### Agregar columnas y combinar Data Frames

In [ ]:
# Agregando una fila (record)
# Creamos un data.frame() con los datos (mismo tamaño al data frame a agregar)
# Utilizamos rbind("data frame a editar", "nuevo data frame")


In [ ]:
# Agregando una columna (variable)
# Creamos un vector con los datos correspondientes a cada inviduo(record),
# este vector debe almacenarse en un objeto con el nombre de la variable
# Utilizamos cbind("data frame a editar", "vector a agregar")

In [28]:
# Vamos a manipular un poco el data frame con el operador $

datos$name # Seleccionar una columna por nombre
datos$retiro <- (60 - datos$age) # Calcular una nueva variable
datos$estado_civil <- c("S", "S", "V", "C", "C", "S", "C") # Nueva variable
datos[,3] #Seleccionar la columna 3 
datos
onlymale <- datos[datos$gender == "M",]
onlymale
ageonlymale  <- onlymale[,c("gender", "age")]
ageonlymale
e_civil<-  subset.data.frame(datos, select = c(name, estado_civil))
e_civil

[1] Ana    Daniel Chris  Mary   Albert Flor   Gendry
Levels: Albert Ana Chris Daniel Flor Gendry Mary

[1] 23 27 54 34 46 22 45

name   gender age retiro estado_civil
1 Ana    F      23  37     S           
2 Daniel M      27  33     S           
3 Chris  M      54   6     V           
4 Mary   F      34  26     C           
5 Albert M      46  14     C           
6 Flor   F      22  38     S           
7 Gendry M      45  15     C

name   gender age retiro estado_civil
2 Daniel M      27  33     S           
3 Chris  M      54   6     V           
5 Albert M      46  14     C           
7 Gendry M      45  15     C

gender age
2 M      27 
3 M      54 
5 M      46 
7 M      45

name   estado_civil
1 Ana    S           
2 Daniel S           
3 Chris  V           
4 Mary   C           
5 Albert C           
6 Flor   S           
7 Gendry C

## Matrices

Es un objeto bidimensonal, se puede reconocer como varios vectores guardados juntos. Su tamaño está definido por su número de columnas y de filas.

Normalmente, describimos  una matriz `A` como una matriz `m` x `n`, `A` teniendo exactamente `m` filas y `n` columnas, con un total de `mn`, done cada cada entrada tiene una posición única dada por una fila y una columna específicas.

Para crear una matriz en R usamos el comando de `matrix` y proveemos las entradas de la matriz en forma de vector.

In [13]:
# Creemos un vector o elijamos uno de los anteriores
# Utilicemos el comando matrix
# Por defecto lo ordena por columnas (verticalmente), para cambiar : byrow = TRUE
# Debemos asegurarnos que la longitud del vector coincida con el número de filas y columnas deseadas.
# Qué sucede si no introducimos ncol y/o nrow, R devuelve una matriz de una sola columna.

In [19]:
m  <- 34:39
A  <- matrix(m, ncol = 2, nrow = 3)
A

[,1] [,2]
[1,] 34   37  
[2,] 35   38  
[3,] 36   39

In [ ]:
#Construir matriz con rbind [filas], cbind [columnas]

In [3]:
# Elegir el conjunto de datos euro.cross
# Buscar información sobre el conjunto de datos
# Cuál es la dimensión de esa matriz A, cuántas filas y cuántas columnas
# Acceder al elemento 8,9 n de la matriz anterior
# Acceder a la 4 columna
# Acceder a la 6 fila
# Mostrar la diagonal

Si queremos omitir alguna de las filas o columnas simplemente los seleccionamos como se hace normalmente con [] y se pone un (-) delante la fila o columna a omitir

In [ ]:
# Crear una matriz A de números consecutivos de 7 filas y 4 columnas
# Omitir las filas 3 y 6, y las columnas 2 y 3

In [ ]:
# Ahora, si lo que queremos es reescribir
# Ubicamos la fila o columna que queremos reescribir y le asignamos un valor
# Utiliza la matriz anterior, A
# Crea una nueva matriz B
# Reemplaza la posición 3, 4
# Reemplaza la primera columna por el número 29 (Usar rep())
# Reemplaza la segunda columna por números consecutivos
# Reemplaza las entradas 1, 3; 3, 3; 5,3 Pista: ¿Cuál es el patrón?
# Reemplaza la diagonal por el número 1

In [5]:
B[c(1, 3, 5),3] <- rep(x = 33, times = 3)

ERROR: Error in B[c(1, 3, 5), 3] <- rep(x = 33, times = 3): objeto 'B' no encontrado


In [30]:
# Cambiemos los nombres de las columnas y filas 
# rownames
# colnames

Podemos realizar las mismas operaciones con las matrices que con los vecctores, es decir, podemos sumar, restar y hasta multiplicar, pero esto solo será posible si las matrices tienen las mismas dimensiones, dichas operaciones se realizaran elemento a elemento.

No hay que confundir la multiplicación matricial, que de hecho tiene un operador diferente

In [42]:
M  <- matrix(c(10:19), nrow = 5, ncol = 2)
G  <- matrix(c(0:9), nrow = 5 , ncol = 2)
H  <- matrix(c(5:12), nrow = 2, ncol = 4)
M + G
# M + H       No tiene las mismas dimensiones
M * G
# M * H       No tiene las mismas dimensiones
M%*%H
# M%*%G       No cumple con las condiciones de la multiplicación de matrices

[,1] [,2]
[1,] 10   20  
[2,] 12   22  
[3,] 14   24  
[4,] 16   26  
[5,] 18   28

[,1] [,2]
[1,]  0    75 
[2,] 11    96 
[3,] 24   119 
[4,] 39   144 
[5,] 56   171

[,1] [,2] [,3] [,4]
[1,] 140  190  240  290 
[2,] 151  205  259  313 
[3,] 162  220  278  336 
[4,] 173  235  297  359 
[5,] 184  250  316  382