# Estructuras de datos

Para R existen distintas estructuras de datos que pueden ser identificadas con los siguientes comandos

In [6]:
# str()
# class()

## Vectores

Anteriormente hemos creado vectores de longitud 1 cuando guardamos en un objeto un único número.
También observamos que podemos crear vectores con las funciones `c()` y `scan()`.

Pero también podemos crearlos con secuencias, repeticiones, y la función `paste()`   

In [11]:
#Generando secuencias de datos 
#Operador
1:8
#Función seq()
seq (1,8)
seq (1,8, by= .5) # Cambiando valores por defecto de los argumentos
a <- seq (1,8, length=15)
a
#Función rep()
rep (7,5)
rep (1:5,3)
b <- rep (c("A", "B", "C"), 3)
b
#Función paste()
paste("T",1:4)
c <- paste("T",1:4,sep=".")
c
new <- c(2, 4, 67, 43, 13, 7, 22, 30, 51)
# Función sort()
sort(new) # Devuelve los argumentos ordenados
# Función order()
order(new) # Devuelve la posición de los argumentos ordenados
# Función rank()
rank(new) # Devuelve el ranking de los elementos del vector en su posición original
new

[1] 1 2 3 4 5 6 7 8

[1] 1 2 3 4 5 6 7 8

[1] 1.0 1.5 2.0 2.5 3.0 3.5 4.0 4.5 5.0 5.5 6.0 6.5 7.0 7.5 8.0

[1] 1.0 1.5 2.0 2.5 3.0 3.5 4.0 4.5 5.0 5.5 6.0 6.5 7.0 7.5 8.0

[1] 7 7 7 7 7

[1] 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5

[1] "A" "B" "C" "A" "B" "C" "A" "B" "C"

[1] "T 1" "T 2" "T 3" "T 4"

[1] "T.1" "T.2" "T.3" "T.4"

[1]  2  4  7 13 22 30 43 51 67

[1] 1 2 6 5 7 8 4 9 3

[1] 1 2 9 7 4 3 5 6 8

[1]  2  4 67 43 13  7 22 30 51

Una de las principales características más importantes de R es la posibilidad de usar un vector como argumento de las funciones y así utilizar todos los elementos del mismo.

In [8]:
# Crear un vector x de 15 números
# Aplicar función max()
# Crear un vector d con los vectores a, b, c

Existirán otras veces en las que necesitaremos acceder específicamente a un elemento del vector, como este tiene una sola dimensión, ubicaremos entre `[]` la posición del elemento a escoger. En R el índice comienza en 1.

In [3]:
# Seleccionar el elemento 7 de x
# Seleccionar elementos del 9 al 12

Podemos ordenar el vector en forma ascendente o decreciente con la función `sort()` y encontrar su longitud con `length()`.

In [ ]:
# Ordenar x en orden ascendente
# Averiguar la longitud de x

### Operaciones con vectores

Suma, resta, división, exponenciación, se definen de elemento a elemento entre vectores

In [22]:
# Suma entre dos vectores de longitud 4
# Resta de dos vectores de longitud 2
# Multiplicación de dos vectores de longitud 3
# Eleva a potencia 
    #(2, 3, 4)^(3:1)
#Probemos los operadores lógicos >,<,=

## Matrices

Es un objeto bidimensonal, se puede reconocer como varios vectores guardados juntos; por esto, al igual que para los vectores, no es posible tener elementos de diferentes clases dentro de una misma matriz. Su tamaño está definido por su número de columnas y de filas.

Normalmente, describimos  una matriz `A` como una matriz `m` x `n`, `A` teniendo exactamente `m` filas y `n` columnas, con un total de `mn`, donde cada entrada tiene una posición única dada por una fila y una columna específicas.

Para crear una matriz en R usamos el comando de `matrix` y proveemos las entradas de la matriz en forma de vector.

In [13]:
# Creemos un vector o elijamos uno de los anteriores
# Utilicemos el comando matrix
# Por defecto lo ordena por columnas (verticalmente), para cambiar : byrow = TRUE
# Debemos asegurarnos que la longitud del vector coincida con el número de filas y columnas deseadas.
# Qué sucede si no introducimos ncol y/o nrow, R devuelve una matriz de una sola columna.

In [4]:
m  <- 34:39
A  <- matrix(m, ncol = 2, nrow = 3)
AA  <- matrix(m)
A
AA

[,1] [,2]
[1,] 34   37  
[2,] 35   38  
[3,] 36   39

[,1]
[1,] 34  
[2,] 35  
[3,] 36  
[4,] 37  
[5,] 38  
[6,] 39

In [ ]:
#Construir matriz con rbind [filas], cbind [columnas]

In [3]:
# Elegir el conjunto de datos euro.cross
# Buscar información sobre el conjunto de datos
# Cuál es la dimensión de esa matriz A, cuántas filas y cuántas columnas
# Acceder al elemento 8,9 n de la matriz anterior
# Acceder a la 4 columna
# Acceder a la 6 fila
# Mostrar la diagonal diag()

Si queremos omitir alguna de las filas o columnas simplemente los seleccionamos como se hace normalmente con [] y se pone un (-) delante la fila o columna a omitir

In [ ]:
# Crear una matriz A de números consecutivos de 7 filas y 4 columnas
# Omitir las filas 3 y 6, y las columnas 2 y 3

In [ ]:
# Ahora, si lo queremos reescribir
# Ubicamos la fila o columna que queremos reescribir y le asignamos un valor
# Utiliza la matriz anterior, A
# Crea una nueva matriz B
# Reemplaza la posición 3, 4
# Reemplaza la primera columna por el número 29 (Usar rep())
# Reemplaza la segunda columna por números consecutivos
# Reemplaza las entradas 1, 3; 3, 3; 5,3 Pista: ¿Cuál es el patrón?
# Reemplaza la diagonal por el número 1

In [5]:
B[c(1, 3, 5),3] <- rep(x = 33, times = 3)

ERROR: Error in B[c(1, 3, 5), 3] <- rep(x = 33, times = 3): objeto 'B' no encontrado


In [30]:
# Cambiemos los nombres de las columnas y filas 
# rownames
# colnames

Podemos realizar las mismas operaciones con las matrices que con los vectores, es decir, podemos sumar, restar y hasta multiplicar, pero esto solo será posible si las matrices tienen las mismas dimensiones, dichas operaciones se realizarán elemento a elemento.

No hay que confundir la multiplicación matricial, que de hecho tiene un operador diferente:

In [22]:
M  <- matrix(c(10:19), nrow = 5, ncol = 2)
G  <- matrix(c(0:9), nrow = 5 , ncol = 2)
H  <- matrix(c(5:12), nrow = 2, ncol = 4)
M + G
# M + H       No tiene las mismas dimensiones
M * G
# M * H       No tiene las mismas dimensiones
M%*%H
# M%*%G       No cumple con las condiciones de la multiplicación de matrices

[,1] [,2]
[1,] 10   20  
[2,] 12   22  
[3,] 14   24  
[4,] 16   26  
[5,] 18   28

[,1] [,2]
[1,]  0    75 
[2,] 11    96 
[3,] 24   119 
[4,] 39   144 
[5,] 56   171

[,1] [,2] [,3] [,4]
[1,] 140  190  240  290 
[2,] 151  205  259  313 
[3,] 162  220  278  336 
[4,] 173  235  297  359 
[5,] 184  250  316  382

Otras operaciones importantes son, la transpuesta, la inversa y el determinante de una matriz.

In [ ]:
# t() transpuesta
# solve () inversa
# det() determinante

## Arreglos

Así como las matrices son la extensión de vectores, los arreglos son la extensión de matrices y por lo tanto también de los vectores.
Un arreglo puede ser considerada una colección de matrices igualmente dimensionadas. Todavía tenemos un número fijo de filas y columnas y una nueva dimensión "layer" o capa.

![Arreglos](../Images/022-arrays.png)

Un arreglo de 3 x 4 x 2. [fila, columna, capa]

In [3]:
# Un ejemplo sencillo sería:
AR <- array(data=1:24,dim=c(3,4,2))
print(AR)

, , 1

     [,1] [,2] [,3] [,4]
[1,]    1    4    7   10
[2,]    2    5    8   11
[3,]    3    6    9   12

, , 2

     [,1] [,2] [,3] [,4]
[1,]   13   16   19   22
[2,]   14   17   20   23
[3,]   15   18   21   24



Para crear subconjuntos, hacer extracciones y reemplazos se utiliza la misma lógica de las otras estructuras de datos, utilizando `[]` y las posiciones respectivas.

In [17]:
# Seleccionar la segunda fila de la primera capa
# Seleccionar de la primera fila, las columnas 3 y 4 de la segunda capa
# Seleccionar la fila 1 y 2 de las dos capas
# Usar print() para ver los resultad
# Reemplaza la tercera fila de la segunda capa por una repetición del número 4

## Data Frame


Es un objeto bidimensional (filas x columnas).

R trata las columnas (llamadas variables) como distintas variables (mismo tipo) y las filas(llamadas records) representan las observaciones (diferentes tipos).
Los Data Frames son rectangulares y los espacios vacíos se llenan con NA, **sus elementos tienen la misma longitud**.

Se pueden crear con la funcion `data.frame()` y puedes seleccionar una columna usando el operador `$`. 



In [20]:
# Creemos 3 vectores l, m, n de longitud 6
name <- c("Ana", "Daniel", "Chris", "Mary", "Albert", "Flor", "Gendry")
gender <- c("F", "M", "M", "F", "M", "F", "M")
age <- c(23, 27, 54, 34, 46, 22, 45)
datos <- data.frame(name, gender, age)
datos

name   gender age
1 Ana    F      23 
2 Daniel M      27 
3 Chris  M      54 
4 Mary   F      34 
5 Albert M      46 
6 Flor   F      22 
7 Gendry M      45

La mayoría de las veces nos vamos a encontrar con bases de datos gigantes, que no va a ser muy práctico desplegar en la consola, por lo que R presenta varias funciones que nos permiten extraer información y observar algunas características de los datos. Veamos algunas:

Carguemos un conjunto de datos, utilizando la función `data()` (podemos encontrar más información sobre los conjuntos de datos en wikipedia, por ejemplo: https://es.wikipedia.org/wiki/Iris_flor_conjunto_de_datos )

In [ ]:
data()
# Elegir un dataset y aplicar las siguientes funciones
# head()
# tail()
# fix()
# edit()
# str()
# summary()

Podemos conocer algunas características del data frame con las siguientes funciones:

In [20]:
nrow() #Introducir dentro del paréntesis el conjunto seleccionado
ncol()
dim ()

ERROR: Error in nrow(): el argumento "x" está ausente, sin valor por omisión


### Agregar columnas y combinar Data Frames

In [1]:
# Agregando una fila (record)
# Creamos un data.frame() con los datos (mismo tamaño al data frame a agregar)
# Utilizamos rbind("data frame a editar", "nuevo data frame")

In [ ]:
# Agregando una columna (variable)
# Creamos un vector con los datos correspondientes a cada inviduo(record),
# este vector debe almacenarse en un objeto con el nombre de la variable
# Utilizamos cbind("data frame a editar", "vector a agregar")

In [21]:
# Vamos a manipular un poco el data frame con el operador $

datos$name # Seleccionar una columna por nombre
datos$retiro <- (60 - datos$age) # Calcular una nueva variable
datos$estado_civil <- c("S", "S", "V", "C", "C", "S", "C") # Nueva variable
datos[,3] #Seleccionar la columna 3 
datos
onlymale <- datos[datos$gender == "M",]
onlymale
ageonlymale  <- onlymale[,c("gender", "age")]
ageonlymale
e_civil<-  subset.data.frame(datos, select = c(name, estado_civil))
e_civil

[1] Ana    Daniel Chris  Mary   Albert Flor   Gendry
Levels: Albert Ana Chris Daniel Flor Gendry Mary

[1] 23 27 54 34 46 22 45

name   gender age retiro estado_civil
1 Ana    F      23  37     S           
2 Daniel M      27  33     S           
3 Chris  M      54   6     V           
4 Mary   F      34  26     C           
5 Albert M      46  14     C           
6 Flor   F      22  38     S           
7 Gendry M      45  15     C

name   gender age retiro estado_civil
2 Daniel M      27  33     S           
3 Chris  M      54   6     V           
5 Albert M      46  14     C           
7 Gendry M      45  15     C

gender age
2 M      27 
3 M      54 
5 M      46 
7 M      45

name   estado_civil
1 Ana    S           
2 Daniel S           
3 Chris  V           
4 Mary   C           
5 Albert C           
6 Flor   S           
7 Gendry C

## Listas

Es una clase de datos quede  puede contener 0 o más elementos, cada uno de los cuales puede ser de un tipo distinto. Es especialmente útil porque una sola lista puede contener una matriz numérica, una cadena de caracteres, factores, e incluso otra lista.

In [54]:
# Creemos un vector de números, uno de caracteres, una matriz, y un data frame 
e1  <- c(9:1)
e2 <- c("Ana", "María", "Robert", "Luis")
e3  <- M
e4  <- datos
mylist  <- list(e1, e2, e3, e4)
mylist

[[1]]
[1] 9 8 7 6 5 4 3 2 1

[[2]]
[1] "Ana"    "María"  "Robert" "Luis"  

[[3]]
     [,1] [,2]
[1,]   10   15
[2,]   11   16
[3,]   12   17
[4,]   13   18
[5,]   14   19

[[4]]
    name gender age retiro estado_civil
1    Ana      F  23     37            S
2 Daniel      M  27     33            S
3  Chris      M  54      6            V
4   Mary      F  34     26            C
5 Albert      M  46     14            C
6   Flor      F  22     38            S
7 Gendry      M  45     15            C

In [55]:
# Nombremos cada uno de los elementos dentro de la lista
names(mylist) <- c("Vector1", "Vector2", "Matriz", "DataFrame")
mylist

$Vector1
[1] 9 8 7 6 5 4 3 2 1

$Vector2
[1] "Ana"    "María"  "Robert" "Luis"  

$Matriz
     [,1] [,2]
[1,]   10   15
[2,]   11   16
[3,]   12   17
[4,]   13   18
[5,]   14   19

$DataFrame
    name gender age retiro estado_civil
1    Ana      F  23     37            S
2 Daniel      M  27     33            S
3  Chris      M  54      6            V
4   Mary      F  34     26            C
5 Albert      M  46     14            C
6   Flor      F  22     38            S
7 Gendry      M  45     15            C

In [57]:
# También podemos nombrar los elementos de la siguiente manera
mylist <- list(vector11 = e1, vector22 = e2, matriz11 = e3, dataframe11 = e4)
# Otra opción menos elegantes es escribir cada elemento dentro de los argumentos
names(mylist)
length(mylist)

[1] "vector11"    "vector22"    "matriz11"    "dataframe11"

[1] 4

In [34]:
#Para acceder a uno de los elementos utilizamos [[]]
mylist[[3]]

[,1] [,2]
[1,] 10   15  
[2,] 11   16  
[3,] 12   17  
[4,] 13   18  
[5,] 14   19

In [38]:
#También podemos acceder a alguna entrada, fila o columna específicos de cada elemento
mylist[[3]][3,2]
# Además de hacer operaciones con ese elemento particular (dependiento del tipo)
nuevo <- mylist[[1]] + 3
nuevo

[1] 17

[1] 12 11 10  9  8  7  6  5  4

In [45]:
# Ahora podemos acceder a ellos por sus nombres
mylist$vector22

[1] "Ana"    "María"  "Robert" "Luis"

In [58]:
mylist[[2]] <- paste(c(mylist$vector22, "Luisa", "Rosa"))
mylist$vector22
mylist[[1]]  <- paste(c(mylist[[1]], 4, 5))
mylist$vector11

[1] "Ana"    "María"  "Robert" "Luis"   "Luisa"  "Rosa"

[1] "9" "8" "7" "6" "5" "4" "3" "2" "1" "4" "5"

### Listas dentro de listas

In [61]:
mynewlist  <- list(logical=c(T,T,F,F,F,T,F,F,T,T), string = "hello friend", matriz2 = mylist$matriz*3)
mynewlist
mynewlist$lista <- mylist
mynewlist

$logical
 [1]  TRUE  TRUE FALSE FALSE FALSE  TRUE FALSE FALSE  TRUE  TRUE

$string
[1] "hello friend"

$matriz2
     [,1] [,2]
[1,]   30   45
[2,]   33   48
[3,]   36   51
[4,]   39   54
[5,]   42   57

$logical
 [1]  TRUE  TRUE FALSE FALSE FALSE  TRUE FALSE FALSE  TRUE  TRUE

$string
[1] "hello friend"

$matriz2
     [,1] [,2]
[1,]   30   45
[2,]   33   48
[3,]   36   51
[4,]   39   54
[5,]   42   57

$lista
$lista$vector11
 [1] "9" "8" "7" "6" "5" "4" "3" "2" "1" "4" "5"

$lista$vector22
[1] "Ana"    "María"  "Robert" "Luis"   "Luisa"  "Rosa"  

$lista$matriz11
     [,1] [,2]
[1,]   10   15
[2,]   11   16
[3,]   12   17
[4,]   13   18
[5,]   14   19

$lista$dataframe11
    name gender age retiro estado_civil
1    Ana      F  23     37            S
2 Daniel      M  27     33            S
3  Chris      M  54      6            V
4   Mary      F  34     26            C
5 Albert      M  46     14            C
6   Flor      F  22     38            S
7 Gendry      M  45     15            C

In [63]:
# Para acceder a un elemento de la lista anidada, se puede hacer de diferentes formas
mynewlist$lista$vector11[4:7]
mynewlist[[4]][[1]][4:7]
mynewlist[[4]]$vector11[4:7]
mynewlist$lista[[1]][4:7]

[1] "6" "5" "4" "3"

[1] "6" "5" "4" "3"

[1] "6" "5" "4" "3"

[1] "6" "5" "4" "3"

## Convirtiendo de un objeto a otro

### De Matriz a Data Frame

Ambos objetos son similares, son rectangulares y bidimensionales. La conversión se hace con el comando `as.data.frame()`

In [80]:
colnames (e3) <- c("1-14", "15-19")
print(e3)
class(e3)
e3df <- as.data.frame(e3)
print(e3df)
class(e3df)

     1-14 15-19
[1,]   10    15
[2,]   11    16
[3,]   12    17
[4,]   13    18
[5,]   14    19


[1] "matrix"

  1-14 15-19
1   10    15
2   11    16
3   12    17
4   13    18
5   14    19


[1] "data.frame"

### Convertir un Data Frame en una Matriz

De la misma forma se puede convertir un data frame en una matriz con el comando `as.matrix()`. Cuando el data frame tiene variables mezcladas entre números y caracteres, el resultado es una matriz de caracteres, mientras que si el data frame es todo numérico, la matriz también lo será.

In [79]:
class(e3df)
e3m  <- as.matrix(e3df)
print(e3m)
class(e3m)

[1] "data.frame"

     1-14 15-19
[1,]   10    15
[2,]   11    16
[3,]   12    17
[4,]   13    18
[5,]   14    19


[1] "matrix"

In [78]:
# Siendo mixta
class(datos)
matrizdatos <- as.matrix(datos)
class(matrizdatos)
print(matrizdatos)

[1] "data.frame"

[1] "matrix"

     name     gender age  retiro estado_civil
[1,] "Ana"    "F"    "23" "37"   "S"         
[2,] "Daniel" "M"    "27" "33"   "S"         
[3,] "Chris"  "M"    "54" " 6"   "V"         
[4,] "Mary"   "F"    "34" "26"   "C"         
[5,] "Albert" "M"    "46" "14"   "C"         
[6,] "Flor"   "F"    "22" "38"   "S"         
[7,] "Gendry" "M"    "45" "15"   "C"         


### Convertir un Data Frame en una Lista

In [91]:
class(datos)
list.datos  <- as.list(datos)
class(list.datos)
list.datos

[1] "data.frame"

[1] "list"

$name
[1] Ana    Daniel Chris  Mary   Albert Flor   Gendry
Levels: Albert Ana Chris Daniel Flor Gendry Mary

$gender
[1] F M M F M F M
Levels: F M

$age
[1] 23 27 54 34 46 22 45

$retiro
[1] 37 33  6 26 14 38 15

$estado_civil
[1] "S" "S" "V" "C" "C" "S" "C"

### Convertir matriz en lista

In [90]:
class(e3)
list.e3  <- as.list(as.data.frame(e3))
class(list.e3)
list.e3

[1] "matrix"

[1] "list"

$`1-14`
[1] 10 11 12 13 14

$`15-19`
[1] 15 16 17 18 19

### Cuando todos los elementos de la lista tiene la misma longitud:

#### Convertir una Lista en Data Frame 

In [92]:
class(list.datos)
frame.datos  <- data.frame(list.datos)
print(frame.datos)
class(frame.datos)

[1] "list"

    name gender age retiro estado_civil
1    Ana      F  23     37            S
2 Daniel      M  27     33            S
3  Chris      M  54      6            V
4   Mary      F  34     26            C
5 Albert      M  46     14            C
6   Flor      F  22     38            S
7 Gendry      M  45     15            C


[1] "data.frame"

#### Convertir una Lista en una Matriz

In [93]:
class(list.datos)
matriz.datos  <-  as.matrix(data.frame(list.datos))
print(matriz.datos)
class(matriz.datos)

[1] "list"

     name     gender age  retiro estado_civil
[1,] "Ana"    "F"    "23" "37"   "S"         
[2,] "Daniel" "M"    "27" "33"   "S"         
[3,] "Chris"  "M"    "54" " 6"   "V"         
[4,] "Mary"   "F"    "34" "26"   "C"         
[5,] "Albert" "M"    "46" "14"   "C"         
[6,] "Flor"   "F"    "22" "38"   "S"         
[7,] "Gendry" "M"    "45" "15"   "C"         


[1] "matrix"

Cuando la lista de objetos contiene elementos de diferentes longitudes, la forma mas simple para convertir las listas es extrayendo los componentes de la lista en vectores separados, rellenarlos con elementos `NA` para igualar las longitudes, y luego reensamblar los vectores en un data frame 

In [102]:
milista <- list(logical=c(T,T,F,F,F,T,T,T), string = c("hello", "friend", ",", "how", "are", "you", "?"), matriz2 = mylist$matriz*3)
milista
logico <- milista$logical
cad  <- milista$string
mat <- milista$matriz2
length(logico)
length(cad)
length(mat)



$logical
[1]  TRUE  TRUE FALSE FALSE FALSE  TRUE  TRUE  TRUE

$string
[1] "hello"  "friend" ","      "how"    "are"    "you"    "?"     

$matriz2
     [,1] [,2]
[1,]   30   45
[2,]   33   48
[3,]   36   51
[4,]   39   54
[5,]   42   57

[1] 8

[1] 7

[1] 10